"""Initial Commit

Revision ID: 98fc48b9eca9
Revises: 
Create Date: 2023-01-28 17:07:58.936880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98fc48b9eca9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ActivityTable',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=1000), nullable=True),
    sa.Column('TimeSpentInMinutes', mysql.INTEGER(), nullable=True),
    sa.Column('Start', sa.DATETIME(), nullable=True),
    sa.Column('Stop', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ActivityTable')
    # ### end Alembic commands ###
